/******************************************************************************
 * Product: Compiere ERP & CRM Smart Business Solution                        *
 * Copyright (C) 1999-2007 ComPiere, Inc. All Rights Reserved.                *
 * This program is free software, you can redistribute it and/or modify it    *
 * under the terms version 2 of the GNU General Public License as published   *
 * by the Free Software Foundation. This program is distributed in the hope   *
 * that it will be useful, but WITHOUT ANY WARRANTY, without even the implied *
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
 * See the GNU General Public License for more details.                       *
 * You should have received a copy of the GNU General Public License along    *
 * with this program, if not, write to the Free Software Foundation, Inc.,    *
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.                     *
 * For the text or an alternative of this public license, you may reach us    *
 * ComPiere, Inc., 3600 Bridge Parkway #102, Redwood City, CA 94065, USA      *
 * or via info@compiere.org or http://www.compiere.org/license.html           *
 *****************************************************************************/
package compiere.model;

import java.sql.*;

import org.compiere.framework.*;
import org.compiere.util.*;


/**
 *	This is a non-working example of a Persistent Business Object.
 *	You would extend the class generated by GenerateModel.java
 *
 *  @author Jorg Janke
 *  @version $Id: MyModelExample.java,v 1.2 2006/07/30 00:51:57 jjanke Exp $
 */
public class MyModelExample extends PO
{
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 	Standard constructor.
	 * 	You must implement this constructor for Compiere Persistency
	 *	@param ctx context
	 *	@param ID the primary key ID
	 *	@param trx transaction
	 */
	public MyModelExample (Ctx ctx, int ID, Trx trx)
	{
		super (ctx, ID, trx);
	}	//	MyModelExample

	/**
	 * 	Optional Load Constructor.
	 * 	You would use this constructor to load several business objects.
	 *  <code>
	 * 	SELECT * FROM MyModelExample WHERE ...
	 *  </code>
	 *  @param ctx context
	 *  @param rs result set
	 *	@param trx transaction
	 */
	public MyModelExample (Ctx ctx, ResultSet rs, Trx trx)
	{
		super (ctx, rs, trx);
	}	//	MyModelExample



	/**
	 * 	Init Persistent Object.
	 * 	You would NOT create this method as it is created by the persistency
	 * 	class generated by GenerateModel.java
	 *	@param ctx	context
	 *	@return PO information
	 */
	@Override
	protected POInfo initPO (Ctx ctx)
	{
		return null;
	}	//	initPO


	@Override
	public int get_Table_ID()
	{
		// TODO Auto-generated method stub
		return 0;
	}

}	//	MyModelExample
