/******************************************************************************
 * Product: Compiere ERP & CRM Smart Business Solution                        *
 * Copyright (C) 1999-2008 Compiere, Inc. All Rights Reserved.                *
 * This program is free software, you can redistribute it and/or modify it    *
 * under the terms version 2 of the GNU General Public License as published   *
 * by the Free Software Foundation. This program is distributed in the hope   *
 * that it will be useful, but WITHOUT ANY WARRANTY, without even the implied *
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
 * See the GNU General Public License for more details.                       *
 * You should have received a copy of the GNU General Public License along    *
 * with this program, if not, write to the Free Software Foundation, Inc.,    *
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.                     *
 * For the text or an alternative of this public license, you may reach us at *
 * Compiere, Inc., 3600 Bridge Parkway #102, Redwood City, CA 94065, USA      *
 * or via info@compiere.org or http://www.compiere.org/license.html           *
 *****************************************************************************/
package org.compiere.model;

/** Generated Model - DO NOT CHANGE */
import java.sql.*;
import org.compiere.framework.*;
import org.compiere.util.*;
/** Generated Model for CM_Container_Trl
 *  @author Jorg Janke (generated) 
 *  @version Release 3.5.1 Dev - $Id: X_CM_Container_Trl.java 8247 2009-12-08 15:26:09Z gwu $ */
public class X_CM_Container_Trl extends PO
{
    /** Standard Constructor
    @param ctx context
    @param CM_Container_Trl_ID id
    @param trx transaction
    */
    public X_CM_Container_Trl (Ctx ctx, int CM_Container_Trl_ID, Trx trx)
    {
        super (ctx, CM_Container_Trl_ID, trx);
        
        /* The following are the mandatory fields for this object.
        
        if (CM_Container_Trl_ID == 0)
        {
            setAD_Language (null);
            setCM_Container_ID (0);
            setIsTranslated (false);
            setName (null);
            
        }
        */
        
    }
    /** Load Constructor 
    @param ctx context
    @param rs result set 
    @param trx transaction
    */
    public X_CM_Container_Trl (Ctx ctx, ResultSet rs, Trx trx)
    {
        super (ctx, rs, trx);
        
    }
    /** Serial Version No */
    private static final long serialVersionUID = 27523942849789L;
    /** Last Updated Timestamp 2009-05-08 14:18:53.0 */
    public static final long updatedMS = 1241817533000L;
    /** AD_Table_ID=864 */
    public static final int Table_ID=864;
    
    /** TableName=CM_Container_Trl */
    public static final String Table_Name="CM_Container_Trl";
    
    /**
     *  Get AD Table ID.
     *  @return AD_Table_ID
     */
    @Override public int get_Table_ID()
    {
        return Table_ID;
        
    }
    /** Set Language.
    @param AD_Language Language for this entity */
    public void setAD_Language (String AD_Language)
    {
        set_ValueNoCheck ("AD_Language", AD_Language);
        
    }
    
    /** Get Language.
    @return Language for this entity */
    public String getAD_Language() 
    {
        return (String)get_Value("AD_Language");
        
    }
    
    /** Get Record ID/ColumnName
    @return ID/ColumnName pair */
    public KeyNamePair getKeyNamePair() 
    {
        return new KeyNamePair(get_ID(), String.valueOf(getAD_Language()));
        
    }
    
    /** Set Web Container.
    @param CM_Container_ID Web Container contains content like images, text etc. */
    public void setCM_Container_ID (int CM_Container_ID)
    {
        if (CM_Container_ID < 1) throw new IllegalArgumentException ("CM_Container_ID is mandatory.");
        set_ValueNoCheck ("CM_Container_ID", Integer.valueOf(CM_Container_ID));
        
    }
    
    /** Get Web Container.
    @return Web Container contains content like images, text etc. */
    public int getCM_Container_ID() 
    {
        return get_ValueAsInt("CM_Container_ID");
        
    }
    
    /** Set ContainerXML.
    @param ContainerXML Autogenerated Container definition as XML Code */
    public void setContainerXML (String ContainerXML)
    {
        set_Value ("ContainerXML", ContainerXML);
        
    }
    
    /** Get ContainerXML.
    @return Autogenerated Container definition as XML Code */
    public String getContainerXML() 
    {
        return (String)get_Value("ContainerXML");
        
    }
    
    /** Set Translated.
    @param IsTranslated This column is translated */
    public void setIsTranslated (boolean IsTranslated)
    {
        set_Value ("IsTranslated", Boolean.valueOf(IsTranslated));
        
    }
    
    /** Get Translated.
    @return This column is translated */
    public boolean isTranslated() 
    {
        return get_ValueAsBoolean("IsTranslated");
        
    }
    
    /** Set Meta Description.
    @param Meta_Description Meta info describing the contents of the page */
    public void setMeta_Description (String Meta_Description)
    {
        set_Value ("Meta_Description", Meta_Description);
        
    }
    
    /** Get Meta Description.
    @return Meta info describing the contents of the page */
    public String getMeta_Description() 
    {
        return (String)get_Value("Meta_Description");
        
    }
    
    /** Set Meta Keywords.
    @param Meta_Keywords Contains the keywords for the content */
    public void setMeta_Keywords (String Meta_Keywords)
    {
        set_Value ("Meta_Keywords", Meta_Keywords);
        
    }
    
    /** Get Meta Keywords.
    @return Contains the keywords for the content */
    public String getMeta_Keywords() 
    {
        return (String)get_Value("Meta_Keywords");
        
    }
    
    /** Set Name.
    @param Name Alphanumeric identifier of the entity */
    public void setName (String Name)
    {
        if (Name == null) throw new IllegalArgumentException ("Name is mandatory.");
        set_Value ("Name", Name);
        
    }
    
    /** Get Name.
    @return Alphanumeric identifier of the entity */
    public String getName() 
    {
        return (String)get_Value("Name");
        
    }
    
    /** Set StructureXML.
    @param StructureXML Autogenerated Container definition as XML Code */
    public void setStructureXML (String StructureXML)
    {
        set_Value ("StructureXML", StructureXML);
        
    }
    
    /** Get StructureXML.
    @return Autogenerated Container definition as XML Code */
    public String getStructureXML() 
    {
        return (String)get_Value("StructureXML");
        
    }
    
    /** Set Title.
    @param Title Title of the Contact */
    public void setTitle (String Title)
    {
        set_Value ("Title", Title);
        
    }
    
    /** Get Title.
    @return Title of the Contact */
    public String getTitle() 
    {
        return (String)get_Value("Title");
        
    }
    
    
}
