/*
 * Generated by XDoclet - Do not edit!
 */
package org.compiere.interfaces;

/**
 * Local home interface for compiere/Status.
 */
public interface StatusLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/compiere/StatusLocal";
   public static final String JNDI_NAME="compiere/StatusLocal";

   public org.compiere.interfaces.StatusLocal create()
      throws javax.ejb.CreateException;

}
